let velocidad = 150
let tipo_giro = 900
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, velocidad)
maqueen.motorStop(maqueen.Motors.M2)
basic.pause(tipo_giro)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(2000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, velocidad)
maqueen.motorStop(maqueen.Motors.M1)
basic.pause(tipo_giro)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, velocidad)
maqueen.motorStop(maqueen.Motors.M1)
basic.pause(tipo_giro)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, velocidad)
maqueen.motorStop(maqueen.Motors.M2)
basic.pause(tipo_giro)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, velocidad)
maqueen.motorStop(maqueen.Motors.M1)
basic.pause(tipo_giro)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(1000)
basic.forever(function () {
	
})
